
const frases = 
[
    {   'Frase': 'La gente dice que no puedes vivir sin amor... yo creo que el oxígeno es más importante.',
        'Autor': 'Sheldon Cooper',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐ ⭐'},
    {   'Frase': 'La vejez es como todo lo demás. Para hacer un éxito de la misma, hay que empezar cuanto antes.',
        'Autor': 'Fred Astaire',
        'Wiki' : '',
        'Tags' : ['Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐ '},
    {   'Frase': 'No presumas de haber sido el primero en mi corazón, si no fuiste suficiente inteligente para ser el último.',
        'Autor': 'Marilyn Monroe',
        'Wiki' : '',
        'Tags' : ['Truth','Deep-thoughts'],
        'Rate' : '⭐ ⭐ '},
    {   'Frase': 'Vivimos en un mundo donde nos escondemos para hacer el amor, mientras la violencia se practica a plena luz del día.',
        'Autor': 'John Lennon',
        'Wiki' : '',
        'Tags' : ['Love','Deep-thoughts','Life'],
        'Rate' : '⭐ ⭐ ⭐'},
    {   'Frase': 'El hombre solitario es una bestia o un dios.',
        'Autor': 'Aristóteles',
        'Wiki' : '',
        'Tags' : ['Be-yourself','Classic'],
        'Rate' : '⭐ ⭐'},
    {   'Frase': 'Cuando comprendes que toda opinión es una visión cargada de historia personal, empezarás a comprender que todo juicio es una confesión.',
        'Autor': 'Nikola Tesla',
        'Wiki' : '',
        'Tags' : ['Fact','Deep-thoughts'],
        'Rate' : '⭐ ⭐ ⭐ ⭐'},
    {   'Frase': 'Deberíamos adquirir el coraje de no ser como todo el mundo',
        'Autor': 'Jean-Paul Satre',
        'Wiki' : '',
        'Tags' : ['Inspirational','Change'],
        'Rate' : '⭐ ⭐ ⭐ ⭐'},
    {   'Frase': 'Si la mayoría de nosotros permanecemos ignorantes de nosotros mismos, es por que el autoconocimiento es doloroso y preferimos los placeres de la ilusión...',
        'Autor': 'Aldous Huxley',
        'Wiki' : '',
        'Tags' : ['Fact','Truth'],
        'Rate' : '⭐ ⭐ ⭐ ⭐ ⭐'},
    {   'Frase': 'Es más fácil engañar a la gente, que convencerla de que han sido engañados.',
        'Autor': 'Mark Twain',
        'Wiki' : '',
        'Tags' : ['Sad-but-true','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐'},
    {   'Frase': 'El verbo amar es difícil de conjugar: su pasado no es perfecto, su presente es solo indicativo y su futuro siempre es condicional',
        'Autor': 'Jean Cocteau',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐ ⭐'},

    {   'Frase': 'Once you eliminate the impossible, whatever remains, no matter how improbable, must be the truth.',
        'Autor': 'Sherlock Holmes',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐'},
    {   'Frase': 'Whenever you find yourself on the side of the majority, it is time to reform.',
        'Autor': 'Mark Twain',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐ ⭐'},
    {   'Frase': 'I\'m not young enough to know everything.',
        'Autor': 'Oscar Wilde',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐ ⭐'},
    {   'Frase': 'to go wrong in one\'s own way is better than to go right in someone else\'s.',
        'Autor': 'Fiodor Dostoievsky',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐'},
    {   'Frase': 'Natural selection will not remove ignorance from future generations.',
        'Autor': 'Richard Dawkins',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐'},
    {   'Frase': "If you're trying to create a company, it's like baking a cake. You have to have all the ingredients in the right proportion.",
        'Autor': 'Elon Musk',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐'},
    {   'Frase': "Success is a lousy teacher. It seduces smart people into thinking they can't lose.",
        'Autor': 'Bill Gates',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐'},
    {   'Frase': "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough.",
        'Autor': 'Mark Zuckerberg',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐'},
    {   'Frase': "Everybody wants a happy ending. Right? But it doesn't always roll that way.",
        'Autor': 'Tony Stark',
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐'},
    {   'Frase': "It's over 9000!",
        'Autor': "Vegeta",
        'Wiki' : '',
        'Tags' : ['Humor','Truth','Life'],
        'Rate' : '⭐ ⭐ ⭐ ⭐'},

]